# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # Kubernetes Master Server
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "kmaster.example.com"
    kmaster.vm.network "private_network", ip: "172.42.42.100"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster"
      v.memory = 2048
      v.cpus = 2
    end
  end

  # kubernetes Worker Node-1
  config.vm.define "kworker1" do |workernode|
    workernode.vm.box = "centos/7"
    workernode.vm.hostname = "kworker1.example.com"
    workernode.vm.network "private_network", ip: "172.42.42.101"
    workernode.vm.provider "virtualbox" do |v|
      v.name = "kworker1"
      v.memory = 1024
      v.cpus = 1
      end
    end

  # kubernetes Worker Node-2
  config.vm.define "kworker2" do |workernode|
    workernode.vm.box = "centos/7"
    workernode.vm.hostname = "kworker2.example.com"
    workernode.vm.network "private_network", ip: "172.42.42.102"
    workernode.vm.provider "virtualbox" do |v|
      v.name = "kworker2"
      v.memory = 1024
      v.cpus = 1
      end
    end
end
